apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    {{- include "argus.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - argus.atlas-ml.org
      secretName: argus-tls
  rules:
    - host: argus.atlas-ml.org
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  labels:
    {{- include "argus.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - argus-api.atlas-ml.org
      secretName: argus-api-tls
  rules:
    - host: argus-api.atlas-ml.org
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 8000