apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    pg: argus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "argus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        pg: argus
        {{- include "argus.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "argus.serviceAccountName" . }}
      containers:
        - name: postgres
          image: "postgres:12"
          ports:
            - name: postgres-http
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.pass }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
      volumes:
        - name: data
          emptyDir: {}