apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "open-ondemand.fullname" . }}-ood
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: slate
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.Instance }}.ondemand.{{ .Values.SLATE.Cluster.DNSName }}
    - {{ .Values.Instance }}.keycloak.{{ .Values.SLATE.Cluster.DNSName }}
    secretName: {{ .Values.Instance}}-open-ondemand
  rules:
  - host: {{ .Values.Instance }}.ondemand.{{ .Values.SLATE.Cluster.DNSName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "open-ondemand.fullname" . }}
          servicePort: 80
  - host: {{ .Values.Instance }}.keycloak.{{ .Values.SLATE.Cluster.DNSName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "open-ondemand.fullname" . }}
          servicePort: 8080
