apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-ondemand.fullname" . }}
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 8080
      protocol: TCP
      name: kc8080
  selector:
    {{- include "open-ondemand.selectorLabels" . | nindent 4 }}
