apiVersion: v1
kind: Service
metadata:
  name: {{ template "basic-auth.fullname" . }}
  labels:
    app: {{ template "basic-auth.name" . }}
    chart: {{ template "basic-auth.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
    protocol: TCP
  selector:
    app: {{ template "basic-auth.name" . }}
    instance: {{ .Values.Instance | quote }}
