apiVersion: v1
kind: Service
metadata:
  name: {{ template "applications-onboarding.fullname" . }}
  labels:
    app: {{ template "applications-onboarding.name" . }}
    chart: {{ template "applications-onboarding.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ template "applications-onboarding.name" . }}
    instance: {{ .Values.Instance }}
release: {{ .Release.Name }}