# Generates app name as "connect-submit-[Instance]"
Instance: ""

CondorConfig:
  # The address of your HTCondor Central Manager
  CollectorHost: 
  # If unspecified, defaults to 9618
  CollectorPort: 9618
  # The port on which the condor components in this deployment should listen. 
  # If your Central manager is within the same Kubernetes cluster, the default
  # value of 9618 will work. Otherwise, you must guess an unused port within 
  # the Kubernetes cluster's NodePort range. THis range is usually, but not
  # always 30000-32767
  ExternalCondorPort: 9618
  # The name of a secret which contains the authentication data needed by this
  # submit host. It must contain two keys:
  # - condor_token: A token issued by the cnetral manager
  # - reverse_password: The passwrd used to issue a token to the central manager 
  #                     on behalf of this submit host
  AuthTokenSecret: auth-token-secret
  # Extra configuration can be added via the ConfigFile parameter
  # ConfigFile: |+
  #   ProjectName = "osg.foo"
  #   SUBMIT_EXPRS = $(SUBMIT_EXPRS) ProjectName 

SystemConfig:
  # Enable CVMFS
  Cvmfs: false
  # these are passed through unchanged to Kubernetes, so they need to be in the
  # correct format
  Cpu: 4000m
  Memory: 8Gi
  # If set, the name of a PersistentVolumeClaim which should be mounted as 
  # backing storage. Mutually exclusive with HostPath. 
  PVCName: 
  # If set, a path on the host system which should be mounted as backing 
  # storage. In multi-node clusters it may advisable to also use a node selector
  # (see below) to ensure that this application attempts to run only on nodes 
  # which have the corresponding filesystem present. Mutually exclusive with
  # PVCName. 
  HostPath: 
  # The path at which the volume specified with either PVCName or HostPath
  # should be mounted. 
  MountLocation: /data
  # A selector expression which should be used to select the nodes on which this 
  # application can run. This may be used, for example, in conjunction with a 
  # node label which indicates nodes which have a particular filesystem 
  # available. 
  # NodeSelector: "hasLustre: \"true\""

UserConfig: 
  # Mode defines where user accounts will come from. Valid options are: sssd and connectapi
  Mode: connectapi
  # If Mode is "connectapi", this is the name of the secret from which the 
  # CI-Connect access token should be obtained. the secret should contain one 
  # key, named API_TOKEN. 
  ConnectToken: connect-token-secret
  ConnectUserSourceGroup: 
  ConnectGroupSourceGroup: 

  # SSSD Configuration: This is only used if UserConfig.Mode is set to 'sssd'
  # You can safely ignore this if you are using the connectapi for UserConfig

  # This represents the entire file which will be written to /etc/sssd/sssd.conf
  # Some reasonable defaults have been provided as an example
  # The following values are needed to support unpriveleged credential caching
  #     krb5_ccname_template = FILE:%d/krb5cc_%U_XXXXXX
  #     krb5_ccachedir = /tmp
  # If Kerberos is used as a SSO solution it is reccomended to handle the ccache differently
  SSSD: |+
    [sssd]
    config_file_version = 2
    reconnection_retries = 3
    sbus_timeout = 30
    services = nss, pam
    domains = ad.example.edu
    [nss]
    filter_groups = root
    filter_users = root
    reconnection_retries = 3
    [pam]
    reconnection_retries = 3
    [domain/ad.example.edu]
    debug_level = 3
    enumerate = false
    cache_credentials = true
    use_fully_qualified_names = false
    auth_provider = krb5
    chpass_provider = krb5
    krb5_realm = AD.EXAMPLE.EDU
    krb5_server = kdc1.example.edu:88,kdc2.example.edu:88
    krb5_auth_timeout = 15
    krb5_store_password_if_offline = true
    krb5_ccname_template = FILE:%d/krb5cc_%U_XXXXXX
    krb5_ccachedir = /tmp
    id_provider = ldap
    access_provider = ldap
    ldap_uri = ldap://ldap.example.edu,ldap://ldap2.example.edu
    ldap_search_base = dc=chpc,dc=example,dc=edu
    ldap_tls_cacert = /etc/pki/tls/certs/ca-bundle.crt
    ldap_tls_reqcert = never
    ldap_krb5_init_creds = true
    ldap_krb5_ticket_lifetime = 86400
    ldap_schema = rfc2307bis
    ldap_group_member = uniqueMember
    override_homedir = /home/%u
    default_shell = /bin/bash
    # Some type of LDAP access filter is required, it is possible to restrict by group
    ldap_access_filter = (uidNumber=*)
