apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "condor-submit.name" . }}-condor-configuration
  labels:
    app: condor-submit
    instance: {{ .Values.Instance | quote}}
data:
  condor_config.local: |+
    COLLECTOR_HOST = {{ .Values.CondorConfig.CollectorHost }}:{{ .Values.CondorConfig.CollectorPort }}
    COLLECTOR_PORT = 
    SHARED_PORT_PORT = {{ .Values.CondorConfig.ExternalCondorPort }}
    COLLECTOR_USES_SHARED_PORT = true
    SCHEDD.USE_SHARED_PORT = true
    MASTER.COLLECTOR_HOST = $(IP_ADDRESS):$(SHARED_PORT_PORT) $(COLLECTOR_HOST)
    SEC_PASSWORD_FILE = /etc/condor/password
    ALLOW_NEGOTIATOR = $(ALLOW_NEGOTIATOR) negotiator@cm
    ALLOW_WRITE = $(HOSTALLOW_WRITE) execute-side@matchsession
{{ if .Values.CondorConfig.ConfigFile }}
{{ .Values.CondorConfig.ConfigFile  | indent 4 }}
{{ end }}
---
{{ if eq .Values.UserConfig.Mode "connectapi" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "condor-submit.name" . }}-provisioner-configuration
  labels:
    app: condor-submit
    instance: {{ .Values.Instance | quote }}
data:
  _config: |+
    #!/bin/sh
    # This file will be sourced before the CI Connect provisioner starts up. You
    # can add anything you like here.
    # Append PATH
    # Apparently '[ -z "$PATH" ]' doesn't work because of some subtlety where Bash 
    # kind-of-sort-of says $PATH is set, even though it doesn't appear in `env`
    export PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"
    export USER_GROUP="{{ .Values.UserConfig.ConnectUserSourceGroup }}"
    export GROUP_GROUP="{{ .Values.UserConfig.ConnectGroupSourceGroup }}"
---
{{ end }}
{{ if eq .Values.UserConfig.Mode "sssd" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "condor-submit.name" . }}-auth-configuration
  labels:
    app: condor-submit
    instance: {{ .Values.Instance | quote }}
data:
  sssd.conf: |+
{{ .Values.UserConfig.SSSD | indent 4 }}
{{ end }}
