# used in SLATE to create a unqiue instance name
instance: default

# Default values for funcx_endpoint.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
funcXServiceAddress: https://api2.funcx.org
image:
  repository: funcx/kube-endpoint
  tag: main-3.10
  pullPolicy: Always

workerDebug: false
workerImage: python:3.10
workerInit: pip install funcx-endpoint>=1.0.10
workerNamespace: default
logDir: /tmp/worker_logs

rbacEnabled: true
nameOverride: funcx-endpoint

initMem: 500Mi
maxMem: 1600Mi
initCPU: 1
maxCPU: 2

initBlocks: 0
minBlocks: 1
maxBlocks: 100
maxWorkersPerPod: 1
maxIdleTime: 3600

# endpoint is required
endpointUUID:

# any additional desired CLI args
endpointCLIargs: --log-to-console

# Will fail until user specifies one of these in their values.yaml
secrets: 
useClientCredentials: false
useUserCredentials: false
