{{- if .Values.notifications.enabled }}
{{- if .Values.notifications.system_status }}
apiVersion: batch/v1
kind: CronJob
metadata:
#  name: {{ include "reana.prefix" . }}-system-status
#  namespace: {{ .Release.Namespace }}
  name: {{ template "reana.fullname" . }}
  labels:
    app: {{ template "reana.name" . }}
    chart: {{ template "reana.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  schedule: "{{ .Values.notifications.system_status }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  {{- if .Values.maintenance.enabled }}
  suspend: true
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "reana.prefixed_infrastructure_svaccount_name" . }}
          containers:
          - name: {{ include "reana.prefix" . }}-system-status
            image: {{ .Values.components.reana_server.image }}
            command:
            - '/bin/sh'
            - '-c'
            args:
            - 'flask reana-admin status-report --email {{ .Values.notifications.email_config.receiver }}'
            {{- if .Values.debug.enabled }}
            tty: true
            stdin: true
            {{- end }}
            env:
            {{- if .Values.reana_hostname }}
            - name: REANA_HOSTNAME
              value: {{ .Values.reana_hostname }}
            {{- end }}
            {{- range $key, $value := .Values.db_env_config }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.debug.enabled }}
            - name: FLASK_ENV
              value:  "development"
            - name: REANA_EMAIL_SMTP_SERVER
              value: {{ printf "%s-mail" (include "reana.prefix" .) }}
            - name: REANA_EMAIL_SMTP_PORT
              value: "30025"
            {{- else }}
            - name: REANA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "reana.prefix" . }}-db-secrets
                  key: user
            - name: REANA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "reana.prefix" . }}-db-secrets
                  key: password
            - name: REANA_EMAIL_SMTP_SERVER
              value: {{ .Values.notifications.email_config.smtp_server }}
            - name: REANA_EMAIL_SMTP_PORT
              value: "{{ .Values.notifications.email_config.smtp_port }}"
            - name: REANA_EMAIL_LOGIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "reana.prefix" . }}-mail-notification-sender-password
                  key: REANA_EMAIL_LOGIN
            - name: REANA_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "reana.prefix" . }}-mail-notification-sender-password
                  key: REANA_EMAIL_PASSWORD
            {{- end }}
            - name: REANA_COMPONENT_PREFIX
              value: {{ include "reana.prefix" . }}
            - name: REANA_EMAIL_SENDER
              value: {{ .Values.notifications.email_config.sender }}
            - name: REANA_ADMIN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "reana.prefix" . }}-admin-access-token
                  key: ADMIN_ACCESS_TOKEN
            - name: REANA_INFRASTRUCTURE_KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: REANA_RUNTIME_KUBERNETES_NAMESPACE
              value: {{ .Values.namespace_runtime | default .Release.Namespace }}
            volumeMounts:
              {{- if .Values.debug.enabled }}
              - mountPath: /code/
                name: reana-code
              {{- end }}
              - mountPath: /var/reana
                name: reana-shared-volume
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          volumes:
          - name: reana-shared-volume
            {{- if not (eq .Values.shared_storage.backend "hostpath") }}
            persistentVolumeClaim:
              claimName: {{ include "reana.prefix" . }}-shared-persistent-volume
              readOnly: false
            {{- else }}
            hostPath:
              path:  /var/reana
            {{- end }}
          - name: reana-code
            hostPath:
              path: /code/reana-server
{{- end }}
{{- end }}
---
{{- if and .Values.quota.enabled (tpl .Values.quota.periodic_update_policy .) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "reana.prefix" . }}-resource-quota-update
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ tpl .Values.quota.periodic_update_policy . }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  {{- if .Values.maintenance.enabled }}
  suspend: true
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "reana.prefix" . }}-resource-quota-update
            image: {{ .Values.components.reana_server.image }}
            command:
            - '/bin/sh'
            - '-c'
            args:
            - 'reana-db quota resource-usage-update'
            {{- if .Values.debug.enabled }}
            tty: true
            stdin: true
            {{- end }}
            env:
            - name: REANA_PERIODIC_RESOURCE_QUOTA_UPDATE_POLICY
              value: "true"
            {{- range $key, $value := .Values.db_env_config }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.debug.enabled }}
            - name: FLASK_ENV
              value:  "development"
            {{- else }}
            - name: REANA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "reana.prefix" . }}-db-secrets
                  key: user
            - name: REANA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "reana.prefix" . }}-db-secrets
                  key: password
            {{- end }}
            volumeMounts:
              {{- if .Values.debug.enabled }}
              - mountPath: /code/
                name: reana-code
              {{- end }}
              - mountPath: /var/reana
                name: reana-shared-volume
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          volumes:
          - name: reana-shared-volume
            {{- if not (eq .Values.shared_storage.backend "hostpath") }}
            persistentVolumeClaim:
              claimName: {{ include "reana.prefix" . }}-shared-persistent-volume
              readOnly: false
            {{- else }}
            hostPath:
              path:  /var/reana
            {{- end }}
          - name: reana-code
            hostPath:
              path: /code/reana-server
{{- end }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "reana.prefix" . }}-retention-rules-apply
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.workspaces.retention_rules.cronjob_schedule }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  {{- if .Values.maintenance.enabled }}
  suspend: true
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "reana.prefix" . }}-retention-rules-apply
            image: {{ .Values.components.reana_server.image }}
            command:
            - '/bin/sh'
            - '-c'
            args:
            - 'flask reana-admin retention-rules-apply'
            {{- if .Values.debug.enabled }}
            tty: true
            stdin: true
            {{- end }}
            env:
            {{- range $key, $value := .Values.db_env_config }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.debug.enabled }}
            - name: FLASK_ENV
              value:  "development"
            {{- else }}
            - name: REANA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "reana.prefix" . }}-db-secrets
                  key: user
            - name: REANA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "reana.prefix" . }}-db-secrets
                  key: password
            {{- end }}
            volumeMounts:
              {{- if .Values.debug.enabled }}
              - mountPath: /code/
                name: reana-code
              {{- end }}
              - mountPath: /var/reana
                name: reana-shared-volume
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          volumes:
          - name: reana-shared-volume
            {{- if not (eq .Values.shared_storage.backend "hostpath") }}
            persistentVolumeClaim:
              claimName: {{ include "reana.prefix" . }}-shared-persistent-volume
              readOnly: false
            {{- else }}
            hostPath:
              path:  /var/reana
            {{- end }}
          - name: reana-code
            hostPath:
              path: /code/reana-server
