apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
#  name: {{ include "reana.prefix" . }}-ingress
#  namespace: {{ .Release.Namespace }}
  name: {{ template "reana.fullname" . }}
  labels: 
    app: {{ template "reana.name" . }}
    chart: {{ template "reana.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.tls }}
  {{- if and .self_signed_cert .secret_name }}
    {{- fail "Cannot set `ingress.tls.secret_name` and `ingress.tls.self_signed_cert` at the same time" }}
  {{- end }}
  {{- if .self_signed_cert }}
  tls:
    - secretName: {{ include "reana.prefix" $ }}-tls-secret
  {{- end }}
  {{- if .secret_name }}
  tls:
    - secretName: {{ .secret_name | quote }}
  {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ include "reana.prefix" . }}-server
              port:
                number: 80
        - path: /oauth
          pathType: Prefix
          backend:
            service:
              name: {{ include "reana.prefix" . }}-server
              port:
                number: 80
        {{- if .Values.components.reana_ui.enabled }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "reana.prefix" . }}-ui
              port:
                number: 80
        {{- end }}
      {{- if .Values.reana_hostname }}
      host: {{ .Values.reana_hostname }}
      {{- end }}
