---
apiVersion: v1
kind: ConfigMap
metadata:
#  name: reana-config
#  namespace: {{ .Release.Namespace }}
  name: {{ template "reana.fullname" . }}
  labels: 
    app: {{ template "reana.name" . }}
    chart: {{ template "reana.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
data:
  ui-config.yaml: |
    announcement: {{ .Values.components.reana_ui.announcement | quote | default "null"  }}
    polling_secs: {{ .Values.components.reana_ui.polling_secs | default 15 }}
    docs_url: {{ .Values.components.reana_ui.docs_url | quote | default "null" }}
    client_pyvenv: {{ .Values.components.reana_ui.client_pyvenv | quote | default "null" }}
    forum_url: {{ .Values.components.reana_ui.forum_url | quote | default "null" }}
    chat_url: {{ .Values.components.reana_ui.chat_url | quote | default "null" }}
    cern_sso: {{ .Values.components.reana_ui.cern_sso | default false }}
    cern_ropo: {{ .Values.components.reana_ui.cern_ropo | default false }}
    hide_signup: {{ .Values.components.reana_ui.hide_signup | default false }}
    admin_email: {{ .Values.notifications.email_config.receiver | quote | default "null" }}
    {{- if or (.Values.components.reana_ui.local_users) (eq (.Values.components.reana_ui.local_users | toString) "<nil>") }}
    local_users: true
    {{- else }}
    local_users: false
    {{- end }}
    {{- if or (.Values.components.reana_server.environment.REANA_USER_EMAIL_CONFIRMATION) (eq (.Values.components.reana_server.environment.REANA_USER_EMAIL_CONFIRMATION | toString) "<nil>") }}
    user_confirmation: true
    {{- else }}
    user_confirmation: false
    {{- end }}
    quota_enabled: {{ .Values.quota.enabled }}
