---
apiVersion: v1
kind: ServiceAccount
metadata:
#  name: {{ include "reana.prefixed_infrastructure_svaccount_name" . }}
  name: {{ template "reana.fullname" . }}
  labels: 
    app: {{ template "reana.name" . }}
    chart: {{ template "reana.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}

{{- if .Values.namespace_runtime }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace_runtime }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reana.prefixed_runtime_svaccount_name" . }}
  namespace: {{ .Values.namespace_runtime }}
{{- end }}
