apiVersion: v1
kind: Pod
metadata:
#  name: hook-postdelete
  name: {{ template "reana.fullname" . }}-post-delete-hook
  labels: 
    app: {{ template "reana.name" . }}
    chart: {{ template "reana.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}

  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": hook-succeeded 
spec:
  containers:
  - name: cleanup-hook-container
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo running post-delete hook after waiting for 30 secs && sleep 30 && /bin/rm -rf /var/reana/*']
    volumeMounts:      
      - mountPath: /var/reana
        name: reana-share

  restartPolicy: Never
  terminationGracePeriodSeconds: 0 
  volumes:
    - name: reana-share  
      hostPath:
        path: /var/reana 
